{
    xtype: 'gvisualization',
    id: 'wb-google-lineChart',
    visualizationPkg: 'linechart',
    visualizationCfg: {
		chartArea : { left : 'auto',
					top : 'auto',
					width : 'auto',
					height : 'auto' },
		curveType : 'none',
		fontSize : '9',
		fontName : 'Arial',
		gridlineColor : '#CCC',
		hAxis : { direction : 1,
				textPosition : 'out',
				textStyle : "{color: 'black', fontName: Arial, fontSize: 9}",
				title : null,
				titleTextStyle : "{color: 'black', fontName: Arial, fontSize: 9}",
				slantedText : 'automatic',
				slantedTextAngle : 30,
				maxAlternation : 2,
				showTextEvery : 'automatic' },
		interpolateNulls : false,
		legend : 'right',
		legendTextStyle : "{color: 'black', fontName: Arial, fontSize: 9}",
		lineWidth : 2,
		pointSize : 7,
		reverseCategories : false,
		title : '',
		titlePosition : 'in',
		titleTextStyle : "{color: 'black', fontName: Arial, fontSize: 9}",
		tooltipTextStyle : "{color: 'black', fontName: Arial, fontSize: 9}",
		vAxis : {baseline : 'automatic',
				baselineColor : 'black',
				direction : 1,
				logScale : false,
				textPosition : 'out',
				textStyle : "{color: 'black', fontName: Arial, fontSize: 9}",
				title : '',
				titleTextStyle : "{color: 'black', fontName: Arial, fontSize: 9}",
				maxValue : 'automatic',
				minValue : 'automatic' }
	},
    store : 'wbGCommonDataStore'
}
